name: Test C code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: compile
      run: make

    - name: compile
      run: make test

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: integration test
      run: make test-dist


  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        poly: [8, 16, 32, 64]
        opt: ["-Os", "", "-O1", "-O2", "-O3"]

    steps:
    - uses: actions/checkout@v2

    - name: test normal
      env:
        CFLAGS: "-fsanitize=address ${{matrix.opt}} ${{ matrix.path }} -DPOLY1305_${{matrix.poly}}BIT"
      run: make clean test

    - name: test slow
      env:
        CFLAGS: "-fsanitize=address ${{matrix.opt}} ${{ matrix.path }} -DPOLY1305_${{matrix.poly}}BIT -DTEST_SLOW_PATH"
      run: make clean test 

  qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Sonarcloud 
      run: |
        export SONAR_SCANNER_VERSION=4.2.0.1873
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip 
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        export SONAR_SCANNER_OPTS="-server"
        curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
        export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
        build-wrapper-linux-x86-64 --out-dir bw-output make clean test
        sonar-scanner \
          -Dsonar.organization=davylandman-github \
          -Dsonar.projectKey=DavyLandman_portable8439 \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.cfamily.build-wrapper-output=bw-output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#    - name: cppcheck
#      uses: deep5050/cppcheck-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN}}
#        force_language: c

    - name: c-linter
      uses: AMReX-Astro/cpp-linter-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
