name: Test C code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: compile
      run: make

    - name: compile
      run: make test

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: integration test
      run: make test-dist

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poly: [8, 16, 32, 64]
        opt: ["-Os", "", "-O1", "-O2", "-O3"]

    steps:
    - uses: actions/checkout@v2

    - name: test normal
      env:
        CFLAGS: "-fsanitize=address ${{matrix.opt}} ${{ matrix.path }} -DPOLY1305_${{matrix.poly}}BIT"
      run: make clean test

    - name: test slow
      env:
        CFLAGS: "-fsanitize=address ${{matrix.opt}} ${{ matrix.path }} -DPOLY1305_${{matrix.poly}}BIT -DTEST_SLOW_PATH"
      run: make clean test 